In [1]:
import pandas as pd
from sklearn.cluster import DBSCAN
from sentence_transformers import SentenceTransformer
import re
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import joblib

In [2]:
df = pd.read_csv("synthetic_logs.csv")
df

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert
...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     2410 non-null   object
 1   source        2410 non-null   object
 2   log_message   2410 non-null   object
 3   target_label  2410 non-null   object
 4   complexity    2410 non-null   object
dtypes: object(5)
memory usage: 94.3+ KB

In [4]:
df.describe()

,timestamp,source,log_message,target_label,complexity
count,2410,2410,2410,2410,2410
unique,2407,6,2265,9,3
top,4/28/2025 20:42,ThirdPartyAPI,Backup completed successfully.,HTTP Status,bert
freq,2,496,60,1017,1903

In [5]:
print(df.source.nunique())
df.source.unique()

6

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [6]:
print(df.target_label.nunique())
df.target_label.unique()

9

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [7]:
df[df.target_label=='System Notification'].sample(10)

,timestamp,source,log_message,target_label,complexity
1961,3/31/2025 4:30,ThirdPartyAPI,Backup ended at 2025-11-15 23:16:45.,System Notification,regex
2253,10/7/2025 2:20,ModernHR,System reboot initiated by user User644.,System Notification,regex
1683,12/13/2025 5:35,ModernCRM,Backup completed successfully.,System Notification,regex
884,4/17/2025 12:13,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex
1874,4/28/2025 17:10,ThirdPartyAPI,Backup started at 2025-05-24 16:51:08.,System Notification,regex
668,9/5/2025 7:14,ModernHR,System reboot initiated by user User297.,System Notification,regex
2183,3/13/2025 7:23,ThirdPartyAPI,File data_7589.csv uploaded successfully by us...,System Notification,regex
2295,8/25/2025 11:35,ThirdPartyAPI,Backup ended at 2025-06-26 20:07:46.,System Notification,regex
14,1/4/2025 1:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,regex
594,9/13/2025 2:57,ThirdPartyAPI,System updated to version 2.0.1.,System Notification,regex

In [8]:
df[df.log_message.str.startswith("System reboot initiated by user")]

,timestamp,source,log_message,target_label,complexity
36,11/19/2025 13:14,BillingSystem,System reboot initiated by user User243.,System Notification,regex
92,12/4/2025 21:20,BillingSystem,System reboot initiated by user User471.,System Notification,regex
139,5/8/2025 16:34,ModernHR,System reboot initiated by user User216.,System Notification,regex
140,9/11/2025 8:49,AnalyticsEngine,System reboot initiated by user User639.,System Notification,regex
161,3/31/2025 19:40,BillingSystem,System reboot initiated by user User819.,System Notification,regex
163,6/6/2025 15:29,BillingSystem,System reboot initiated by user User938.,System Notification,regex
307,4/12/2025 0:41,BillingSystem,System reboot initiated by user User929.,System Notification,regex
365,10/20/2025 22:32,ModernHR,System reboot initiated by user User533.,System Notification,regex
508,4/15/2025 2:04,ThirdPartyAPI,System reboot initiated by user User591.,System Notification,regex
552,9/22/2025 20:54,ModernHR,System reboot initiated by user User421.,System Notification,regex
668,9/5/2025 7:14,ModernHR,System reboot initiated by user User297.,System Notification,regex
693,7/6/2025 21:40,BillingSystem,System reboot initiated by user User159.,System Notification,regex
697,3/13/2025 7:09,BillingSystem,System reboot initiated by user User648.,System Notification,regex
714,9/25/2025 23:35,ThirdPartyAPI,System reboot initiated by user User600.,System Notification,regex
730,5/24/2025 11:08,AnalyticsEngine,System reboot initiated by user User120.,System Notification,regex
800,8/15/2025 12:14,BillingSystem,System reboot initiated by user User901.,System Notification,regex
837,4/9/2025 8:28,AnalyticsEngine,System reboot initiated by user User876.,System Notification,regex
852,3/31/2025 5:20,ModernCRM,System reboot initiated by user User811.,System Notification,regex
865,2/25/2025 1:40,AnalyticsEngine,System reboot initiated by user User964.,System Notification,regex
889,11/30/2025 13:45,ModernHR,System reboot initiated by user User766.,System Notification,regex
896,7/28/2025 11:24,BillingSystem,System reboot initiated by user User765.,System Notification,regex
988,9/11/2025 22:23,BillingSystem,System reboot initiated by user User427.,System Notification,regex
1106,12/28/2025 13:32,ModernHR,System reboot initiated by user User246.,System Notification,regex
1159,8/5/2025 6:52,BillingSystem,System reboot initiated by user User329.,System Notification,regex
1194,7/20/2025 9:10,AnalyticsEngine,System reboot initiated by user User747.,System Notification,regex
1275,7/15/2025 23:37,BillingSystem,System reboot initiated by user User829.,System Notification,regex
1299,7/15/2025 19:19,BillingSystem,System reboot initiated by user User966.,System Notification,regex
1304,8/10/2025 6:18,ThirdPartyAPI,System reboot initiated by user User758.,System Notification,regex
1524,11/30/2025 2:39,ThirdPartyAPI,System reboot initiated by user User278.,System Notification,regex
1562,8/18/2025 4:17,ThirdPartyAPI,System reboot initiated by user User648.,System Notification,regex
1624,12/14/2025 5:14,AnalyticsEngine,System reboot initiated by user User268.,System Notification,regex
1663,10/27/2025 22:04,AnalyticsEngine,System reboot initiated by user User315.,System Notification,regex
1776,2/21/2025 11:56,ModernHR,System reboot initiated by user User155.,System Notification,regex
1803,8/22/2025 6:30,AnalyticsEngine,System reboot initiated by user User204.,System Notification,regex
1804,8/26/2025 21:06,ModernHR,System reboot initiated by user User899.,System Notification,regex
1852,1/26/2025 12:34,AnalyticsEngine,System reboot initiated by user User223.,System Notification,regex
1865,5/11/2025 10:58,AnalyticsEngine,System reboot initiated by user User932.,System Notification,regex
1956,9/26/2025 19:32,ThirdPartyAPI,System reboot initiated by user User264.,System Notification,regex
2003,6/23/2025 17:54,ModernCRM,System reboot initiated by user User517.,System Notification,regex
2014,12/25/2025 4:33,AnalyticsEngine,System reboot initiated by user User293.,System Notification,regex
2043,9/12/2025 20:20,ThirdPartyAPI,System reboot initiated by user User262.,System Notification,regex
2074,9/13/2025 8:43,ModernCRM,System reboot initiated by user User937.,System Notification,regex
2228,9/3/2025 11:24,ModernHR,System reboot initiated by user User179.,System Notification,regex
2243,1/16/2025 7:22,ModernHR,System reboot initiated by user User770.,System Notification,regex
2246,3/2/2025 22:56,ModernHR,System reboot initiated by user User488.,System Notification,regex
2253,10/7/2025 2:20,ModernHR,System reboot initiated by user User644.,System Notification,regex
2317,3/7/2025 5:44,BillingSystem,System reboot initiated by user User724.,System Notification,regex
2360,5/1/2025 4:21,ThirdPartyAPI,System reboot initiated by user User876.,System Notification,regex

## Clusterting

In [9]:
model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight embedding model
model

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [10]:
embeddings = model.encode(df['log_message'].tolist())
embeddings
print(embeddings[:5])

[[-0.10293964  0.03354596 -0.02202605 ...  0.0045779  -0.04259719
   0.00322624]
 [ 0.00804571 -0.03573922  0.04938733 ...  0.01538314 -0.0623095
  -0.02774668]
 [-0.00908224  0.13003927 -0.05275576 ...  0.02014105 -0.05117097
  -0.02930294]
 [-0.09751055  0.04911305 -0.03977426 ...  0.02477494 -0.03546084
  -0.00018604]
 [-0.10468348  0.05926033 -0.02488498 ...  0.0250205  -0.03719303
  -0.02568907]]

In [11]:
clustering = DBSCAN(eps=0.2, min_samples=1, metric='cosine').fit(embeddings)
df['cluster'] = clustering.labels_

In [12]:
df

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0
...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7

In [13]:
df[df.cluster==0]

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0
5,2025-10-09 10:30:31,ModernHR,nova.osapi_compute.wsgi.server [req-f0bffbc3-5...,HTTP Status,bert,0
9,2025-03-30 04:01:45,ModernHR,nova.osapi_compute.wsgi.server [req-2bf7cfee-a...,HTTP Status,bert,0
...,...,...,...,...,...,...
2399,2025-03-08 06:23:00,ThirdPartyAPI,nova.metadata.wsgi.server [req-ba29717b-249a-4...,HTTP Status,bert,0
2401,2025-12-05 15:51:51,ModernCRM,nova.osapi_compute.wsgi.server [req-4bdf00b0-3...,HTTP Status,bert,0
2404,2025-09-18 02:18:30,ThirdPartyAPI,nova.osapi_compute.wsgi.server [req-2c9c783f-3...,HTTP Status,bert,0
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0

In [14]:
# Group by cluster to inspect patterns
clusters = df.groupby('cluster')['log_message'].apply(list)
sorted_clusters = clusters.sort_values(key=lambda x: x.map(len), ascending=False)
sorted_clusters

cluster
0      [nova.osapi_compute.wsgi.server [req-b9718cd8-...
5      [nova.compute.claims [req-a07ac654-8e81-416d-b...
11     [User User685 logged out., User User395 logged...
13     [Backup started at 2025-05-14 07:06:55., Backu...
7      [Multiple bad login attempts detected on user ...
                             ...
131              [Global settings have been compromised]
132                [Admin rights elevated for user 1776]
133    [Task assignment for TeamID 3425 could not com...
134    [System configuration inconsistencies were found]
135                [Admin rights elevated for user 3310]
Name: log_message, Length: 136, dtype: object

In [15]:
print("Clustered Patterns:")
for cluster_id, messages in sorted_clusters.items():
    if len(messages) > 10:
        print(f"Cluster {cluster_id}:")
        for msg in messages[:5]:
            print(f"  {msg}")

Clustered Patterns:
Cluster 0:
  nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
  nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
  nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
  nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
  nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369
Cluster 5:
  nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
  nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
  nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
  nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
  nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited
Cluster 11:
  User User685 logged out.
  User User395 logged in.
  User User225 logged in.
  User User494 logged out.
  User User900 logged in.
Cluster 13:
  Backup started at 2025-05-14 07:06:55.
  Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
  Backup started at 2025-11-14 08:27:43.
  Backup started at 2025-12-09 10:19:11.
Cluster 7:
  Multiple bad login attempts detected on user 8538 account
  Multiple login failures occurred on user 9052 account
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
  Multiple login failures were detected for user 6373
Cluster 8:
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
Cluster 21:
  System updated to version 3.9.1.
  System updated to version 5.5.4.
  System updated to version 4.7.4.
  System updated to version 3.7.7.
  System updated to version 2.6.2.
Cluster 3:
  Shard 6 replication task ended in failure
  Data replication task for shard 14 did not complete
  Data replication task failed for shard 17
  Replication of data to shard 14 failed
  Data replication task for shard 6 did not complete
Cluster 4:
  File data_6169.csv uploaded successfully by user User953.
  File data_3847.csv uploaded successfully by user User175.
  File data_7366.csv uploaded successfully by user User282.
  File data_1206.csv uploaded successfully by user User359.
  File data_1503.csv uploaded successfully by user User151.
Cluster 17:
  Denied access attempt on restricted account Account2682
  Unauthorized login attempt on protected account Account5030
  Account Account9437 blocked due to failed login
  Account Account7999 access denied due to login failure
  Invalid login attempt made on secured account Account7864
Cluster 6:
  Critical system unit error: unit ID Component55
  System component malfunction: component ID Component79
  Critical system element is down: element ID Component96
  Essential system part malfunction: part ID Component6
  Failure occurred in critical system component: component ID Component92
Cluster 32:
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
Cluster 16:
  System reboot initiated by user User243.
  System reboot initiated by user User471.
  System reboot initiated by user User216.
  System reboot initiated by user User639.
  System reboot initiated by user User819.
Cluster 20:
  User 7662 tried to bypass API security measures
  User 2367 failed to provide valid API access credentials
  User 3569 made an unauthorized API request
  Unauthorized user 2968 tried to access restricted API
  User 2186 attempted to access API without proper authorization
Cluster 9:
  Account with ID 5351 created by User634.
  Account with ID 7813 created by User373.
  Account with ID 9827 created by User965.
  Account with ID 2520 created by User546.
  Account with ID 2300 created by User964.
Cluster 1:
  Email service experiencing issues with sending
  Email server encountered a sending fault
  Mail service encountered a delivery glitch
  Service disruption caused by email sending error
  Email system had a problem sending emails
Cluster 10:
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
Cluster 34:
  Abnormal behavior found on server 10, possible security threat
  Security alert: suspicious activity on server 1
  Anomalous activity identified on server 23, security review recommended
  Server 27 experienced potential security incident, review required
  Server 36 experienced potential security incident, review required
Cluster 53:
  Module X experienced an invalid data format issue
  Input format mismatch occurred in module X
  Module X reported an error in input format validation
  Module X failed to process input due to formatting error
  Input data format in module X was invalid or corrupted
Cluster 14:
  Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
  RAID array experienced multiple disk crashes
  Multiple hard drive issues in RAID configuration found
  Identification of multiple faulty disks in RAID array
Cluster 52:
  Service health check was not successful because of SSL certificate validation failures.
  Invalid SSL certificate resulted in a failed service health check.
  Service health check failure was due to an invalid or improperly configured SSL certificate.
  An issue with the SSL certificate caused the service health check to fail.
  Service health check failure was caused by an expired SSL certificate.
Cluster 18:
  Boot process terminated unexpectedly due to kernel issue
  System encountered kernel panic during initialization phase
  Boot process was stopped by kernel malfunction
  System encountered kernel failure during bootup sequence
  Boot sequence failed due to kernel panic
Cluster 42:
  User 5127 has escalated admin privileges without authorization
  User 9745 has escalated to admin level
  User 8483 escalated privileges to admin level
  User 1987 has escalated to admin level
  User 8395 escalated privileges to admin level
Cluster 25:
  System configuration is no longer valid
  Configuration is corrupted throughout the system
  Cross-system configuration failure occurred
  System configuration is experiencing errors
  Configuration malfunction is system-wide
Cluster 59:
  Potential security threat: Admin privilege escalation for user 5130
  Admin privilege escalation alert for user 2893
  Admin privilege escalation alert for user 8532
  Potential security threat: Admin privilege escalation for user 1554
  Warning: Potential admin privilege escalation for user 5720
Cluster 26:
  Privilege elevation detected for user 5038
  Elevation of admin privileges detected for user 6137
  Elevation of admin privileges detected for user 4907
  User 6069 has been granted elevated admin privileges
  Admin privilege elevation warning for user 7574

## Regex Classification

In [16]:
#We found the similar patterns for RegEx after clustering
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message):
            return label
    return None

In [17]:
classify_with_regex("User User123 logged in.")

'User Action'

In [18]:
classify_with_regex("System reboot initiated by user User179.")

'System Notification'

In [19]:
classify_with_regex("Hi, good morning. How are you?")

In [20]:
# Apply regex classification to data frame(df)
df['regex_label'] = df['log_message'].apply(lambda x: classify_with_regex(x))
df[df['regex_label'].notnull()]

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,regex,4,System Notification
14,1/4/2025 1:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,regex,4,System Notification
15,5/1/2025 9:41,ModernCRM,Backup completed successfully.,System Notification,regex,8,System Notification
18,2/22/2025 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,regex,9,User Action
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,regex,11,User Action
...,...,...,...,...,...,...,...
2376,6/27/2025 8:47,ModernCRM,System updated to version 2.0.5.,System Notification,regex,21,System Notification
2381,9/5/2025 6:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex,32,System Notification
2394,4/3/2025 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,regex,32,System Notification
2395,5/2/2025 14:29,ThirdPartyAPI,Backup ended at 2025-05-06 11:23:16.,System Notification,regex,13,System Notification
2403,10/1/2025 1:31,ModernCRM,Backup completed successfully.,System Notification,regex,8,System Notification

In [21]:
df[df['regex_label'].isnull()]

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7,None

## Embeddings Classification

In [22]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex.shape

(1910, 7)

In [23]:
#Based on domain knowledge we find that the logs, where source is Legacy CRM , are quite less
df_legacy = df_non_regex[df_non_regex.source=="LegacyCRM"]
print(df_legacy.shape)
df_legacy

(7, 7)

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
60,2025-10-06 16:55:23,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error,llm,24,None
255,2025-05-03 16:55:35,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning,llm,48,None
377,2025-06-24 12:16:29,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error,llm,62,None
1325,2025-04-17 07:33:44,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error,llm,105,None
1734,2025-04-30 07:47:30,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning,llm,118,None
1826,2025-01-23 10:33:36,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning,llm,122,None
2217,2025-05-12 09:46:54,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error,llm,133,None

In [24]:
#We have enough data samples for rest of the sources
df_non_legacy = df_non_regex[df_non_regex.source!="LegacyCRM"]
print(df_non_legacy.shape)
df_non_legacy

(1903, 7)

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7,None

In [25]:
print(df_non_legacy.source.nunique())
df_non_legacy.source.unique()

5

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [26]:
embeddings_filtered = model.encode(df_non_legacy['log_message'].tolist())
print(len(embeddings_filtered))
embeddings_filtered

1903

array([[-0.10293964,  0.03354596, -0.02202605, ...,  0.0045779 ,
        -0.04259719,  0.00322624],
       [ 0.00804571, -0.03573922,  0.04938733, ...,  0.01538314,
        -0.0623095 , -0.02774668],
       [-0.00908224,  0.13003927, -0.05275576, ...,  0.02014105,
        -0.05117097, -0.02930294],
       ...,
       [-0.04022276,  0.04224361, -0.06610432, ...,  0.02363661,
        -0.00530876,  0.0204446 ],
       [-0.03603453,  0.01960898,  0.10052757, ...,  0.0366811 ,
        -0.02487851, -0.00578846],
       [ 0.01457435,  0.04911828, -0.00301354, ...,  0.01029743,
        -0.00068491,  0.00708858]], shape=(1903, 384), dtype=float32)

In [27]:
X = embeddings_filtered
y = df_non_legacy['target_label'].values

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [29]:
clf = LogisticRegression(max_iter=1000, verbose=1)
clf.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

LogisticRegression(max_iter=1000, verbose=1)

In [30]:
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [31]:
joblib.dump(clf, 'log_classifier.joblib')

['log_classifier.joblib']